"""Initial migration with rework queue

Revision ID: 994ccedd5534
Revises: 
Create Date: 2025-06-01 21:54:04.516411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994ccedd5534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rework_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_approved_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('manager_approval_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('manager_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rework_queue', schema=None) as batch_op:
        batch_op.drop_column('manager_notes')
        batch_op.drop_column('manager_approval_time')
        batch_op.drop_column('manager_approved_by')

    # ### end Alembic commands ###
