"""Add notes column to OperatorLog

Revision ID: 9e66f0361e16
Revises: 28f04ff3c052
Create Date: 2025-06-04 03:24:41.201161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e66f0361e16'
down_revision = '28f04ff3c052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_log', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
